In [6]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.arange(0,20).reshape(4,5), index=['Row1','Row2','Row3','Row4'], columns=['A','B','C','D','E'])
df.head()

       A   B   C   D   E
Row1   0   1   2   3   4
Row2   5   6   7   8   9
Row3  10  11  12  13  14
Row4  15  16  17  18  19

In [15]:
df.to_csv('test.csv', index=False)

In [17]:
df.iloc[0:2,0:3]

      A  B  C
Row1  0  1  2
Row2  5  6  7

In [18]:
df.iloc[0:2,0:3].values

array([[0, 1, 2],
       [5, 6, 7]])